### ISSUE TITLE
佬，能提供下数据和代码学习下吗

### ISSUE THREAD

**Issue by ghost** [guizilaile23/TFRN#1]
佬，能提供下数据和代码学习学习吗，求求了

**Comment by guizilaile23** [comment]
> 佬，能提供下数据和代码学习学习吗，求求了
 sorry  才看到，我尽快上传，稍等哈

**Comment by guizilaile23** [comment]
> 佬，能提供下数据和代码学习学习吗，求求了

hi, the source code has been uploaded on Baidu Netdisk,  please find the link at readme.
